import { resolve } from "path";

import { defineConfig } from "vite";

import { assetpackPlugin } from "./scripts/assetpack-vite-plugin";

// https://vite.dev/config/
export default defineConfig({
  plugins: [assetpackPlugin()],
  server: {
    port: 8080,
    open: "/main-web-cam-border.html",
  },
  build: {
    rollupOptions: {
      input: {
        mainWebCamBorder: resolve(__dirname, "main-web-cam-border.html"),
        planetCircleWebcamBorder: resolve(
          __dirname,
          "planet-circle-webcam-border.html",
        ),
        titlePowerline: resolve(__dirname, "title-powerline.html"),
        logo: resolve(__dirname, "logo.html"),
        proceduralLogo: resolve(__dirname, "procedural-logo.html"),
        background: resolve(__dirname, "background.html"),
        startingSoon: resolve(__dirname, "starting-soon.html"),
        musicBreak: resolve(__dirname, "music-break.html"),
        break: resolve(__dirname, "break.html"),
        planet: resolve(__dirname, "planet.html"),
        aquarium: resolve(__dirname, "aquarium.html"),
        atom: resolve(__dirname, "atom.html"),
        simpleWebCamBorder: resolve(__dirname, "simple-web-cam-border.html"),
        matrixDots: resolve(__dirname, "matrix-dots.html"),
        waveCam: resolve(__dirname, "wavecam.html"),
        trapCam: resolve(__dirname, "trapcam.html"),
        generative: resolve(__dirname, "generative.html"),
        hexCam: resolve(__dirname, "hexcam.html"),
        hexGridCam: resolve(__dirname, "hexgridcam.html"),
        hexLayerCam: resolve(__dirname, "hexlayercam.html"),
        triangulation: resolve(__dirname, "triangulation.html"),
        rain: resolve(__dirname, "rain.html"),
        flightSimulation: resolve(__dirname, "flight-simulation.html"),
        grass: resolve(__dirname, "grass.html"),
        graphBg: resolve(__dirname, "graph-bg.html"),
        starField: resolve(__dirname, "star-field.html"),
        maurerRose: resolve(__dirname, "maurer-rose.html"),
        collatz: resolve(__dirname, "collatz.html"),
        perlinBlobs: resolve(__dirname, "perlin-blobs.html"),
        planetHologram: resolve(__dirname, "planet-hologram.html"),
        particleSplash: resolve(__dirname, "particle-splash.html"),
        plexusConstellation: resolve(__dirname, "plexus-constellation.html"),
        flowField: resolve(__dirname, "flow-field.html"),
        gravitySphere: resolve(__dirname, "gravity-sphere.html"),
        lissajous: resolve(__dirname, "lissajous.html"),
        tunnelVortex: resolve(__dirname, "tunnel-vortex.html"),
        spiralPull: resolve(__dirname, "spiral-pull.html"),
        plasmaWave: resolve(__dirname, "plasma-wave.html"),
        magneticField: resolve(__dirname, "magnetic-field.html"),
        life: resolve(__dirname, "life.html"),
        particleGlobe: resolve(__dirname, "particle-globe.html"),
        auroraBorealis: resolve(__dirname, "aurora-borealis.html"),
        fourierEpicycles: resolve(__dirname, "fourier-epicycles.html"),
        hexRipple: resolve(__dirname, "hex-ripple.html"),
        stippledGeodesic: resolve(__dirname, "stippled-geodesic.html"),
        geodesicSphere: resolve(__dirname, "geodesic-sphere.html"),
        wireframeIcosphere: resolve(__dirname, "wireframe-icosphere.html"),
        nebula: resolve(__dirname, "nebula.html"),
        blackHoleCam: resolve(__dirname, "black-hole-cam.html"),
        nbody: resolve(__dirname, "nbody.html"),
        orbitalMechanics: resolve(__dirname, "orbital-mechanics.html"),
        solarWind: resolve(__dirname, "solar-wind.html"),
        shockWave: resolve(__dirname, "shock-wave.html"),
        boids: resolve(__dirname, "boids.html"),
        linuxBoids: resolve(__dirname, "linux-boids.html"),
        linuxIconMesh: resolve(__dirname, "linux-icon-mesh.html"),
        catppuccinLinuxOverlay: resolve(
          __dirname,
          "catppuccin-linux-overlay.html",
        ),
        emberPentagramOverlay: resolve(
          __dirname,
          "ember-pentagram-overlay.html",
        ),
        verletCloth: resolve(__dirname, "verlet-cloth.html"),
        sph: resolve(__dirname, "sph.html"),
        wireframeSphereCam: resolve(__dirname, "wireframe-sphere-cam.html"),
        cosmicPortal: resolve(__dirname, "cosmic-portal.html"),
        camFrameOverlay: resolve(__dirname, "cam-frame-overlay.html"),
        smokeRingCam: resolve(__dirname, "smoke-ring-cam.html"),
        elasticRings: resolve(__dirname, "elastic-rings.html"),
        galaxyBg: resolve(__dirname, "galaxy-bg.html"),
        pcbBg: resolve(__dirname, "pcb-bg.html"),
        infinity: resolve(__dirname, "infinity.html"),
        topoLandscape: resolve(__dirname, "topo-landscape.html"),
        cubicBlobOverlay: resolve(__dirname, "cubic-blob-overlay.html"),
        cubicBlobFaceOverlay: resolve(
          __dirname,
          "cubic-blob-face-overlay.html",
        ),
        map: resolve(__dirname, "map.html"),
        confidential: resolve(__dirname, "confidential.html"),
        trapnation: resolve(__dirname, "trapnation.html"),
        index: resolve(__dirname, "index.html"),
        smokeBar: resolve(__dirname, "smoke-bar.html"),
        voronoiStippling: resolve(__dirname, "voronoi-stippling.html"),
        crystalcam: resolve(__dirname, "crystalcam.html"),
        figureEightTorus: resolve(__dirname, "figure-eight-torus.html"),
        wavyCam: resolve(__dirname, "wavy-cam.html"),
        fluidCircleCam: resolve(__dirname, "fluid-circle-cam.html"),
        fluidCatppuccinRingsCam: resolve(
          __dirname,
          "fluid-catppuccin-rings-cam.html",
        ),
        fluidDottedRingCam: resolve(__dirname, "fluid-dotted-ring-cam.html"),
        fluidMeshRingCam: resolve(__dirname, "fluid-mesh-ring-cam.html"),
        gasCam: resolve(__dirname, "gas-cam.html"),
        worxbendText: resolve(__dirname, "worxbend-text.html"),
        worxbendFluid: resolve(__dirname, "worxbend-fluid.html"),
        worxbendMolecular: resolve(__dirname, "worxbend-molecular.html"),
        startingSoonFluid: resolve(__dirname, "starting-soon-fluid.html"),
        startingSoonParticleMesh: resolve(
          __dirname,
          "starting-soon-particle-mesh.html",
        ),
        streamEndedParticleMesh: resolve(
          __dirname,
          "stream-ended-particle-mesh.html",
        ),
        topography: resolve(__dirname, "topography.html"),
        dottedMesh: resolve(__dirname, "dotted-mesh.html"),
        wavyPlanetMesh: resolve(__dirname, "wavy-planet-mesh.html"),
        catMesh: resolve(__dirname, "cat-mesh.html"),
        nightCityHorizon: resolve(__dirname, "night-city-horizon.html"),
        microbialColony: resolve(__dirname, "microbial-colony.html"),
        avatar: resolve(__dirname, "avatar.html"),
        fluidPaint: resolve(__dirname, "fluid-paint.html"),
        waveBorderCam: resolve(__dirname, "wave-border-cam.html"),
        catCircleCam: resolve(__dirname, "cat-circle-cam.html"),
        animatedLines: resolve(__dirname, "animated-lines.html"),
        mountainNightRailway: resolve(__dirname, "mountain-night-railway.html"),
        tuxBlob: resolve(__dirname, "tux-blob.html"),
        bioluminescentCell: resolve(__dirname, "bioluminescent-cell.html"),
        metaBlobs: resolve(__dirname, "meta-blobs.html"),
        iridescentBlobs: resolve(__dirname, "iridescent-blobs.html"),
        physicsParticles: resolve(__dirname, "physics-particles.html"),
        spaceWarBoids: resolve(__dirname, "space-war-boids.html"),
        amorphousSquareBorder: resolve(
          __dirname,
          "amorphous-square-border.html",
        ),
        darkSunCam: resolve(__dirname, "dark-sun-cam.html"),
        lavenderDashesCam: resolve(__dirname, "lavender-dashes-cam.html"),
      },
    },
  },
  define: {
    APP_VERSION: JSON.stringify(process.env.npm_package_version),
  },
});
